### ISSUE TITLE
volume creation is not derived from volume template

### ISSUE THREAD

**Issue by vinodpop** [HewlettPackard/oneview-ansible-collection#111]
HI team,

when I try to create new volume with existing template it always asks me to mention size and storagepool. where my volume template has all info about volume properties and storage pool.
requirement to create a volume using existing volume template without defining size and storage pool.
is this expected one?

versions:
ansible 2.10.9
Python 3.6.12
hpe-oneview-6.1.0
X-Api-Version: 2600

when using the below content through hpe api its working. similarly gets failed with below error in ansible playbook.
code: (copy paste is not working as expected, below code has no syntax error)
```
---
- hosts: localhost
  become: false
  gather_facts: false
  vars:
     python_interpreter: ~/hpe-ansible/bin/python
  collections:
      - hpe/oneview
  tasks:
    - name: Create a basic connection-less server profile template (using names)
      hpe.oneview.oneview_volume:
        hostname: localhost
        username: Admin
        password: *********
        api_version: 2600
        state: present
        data:
           properties:
             name: 'disk_00000'
             description: 'Test volume with common creation: Storage Pool'
             size: 37580963840
             storagePool: "/rest/storage-pools/pool-id"
           templateUri: "/rest/storage-volume-templates/template_uri"
           #initialScopeUris:
               #- /rest/scopes/resources/rest/storage-volumes/init_uri
           isPermanent: false
      register: datacenters
    - debug:
       msg: "{{ datacenters }}"
```
error:
task_response = self.__get_task_response(task)\n  File \"/home/user/hpe-ansible/lib64/python3.6/site-packages/hpeOneView/resources/task_monitor.py\", line 142, in __get_task_response\n    raise HPEOneViewTaskError(msg, error_code)\nhpeOneView.exceptions.HPEOneViewTaskError: Unable to create or update the volume.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

//vinoth

**Comment by VenkateshRavula** [comment]
Thanks for pointing this issue. We will look into this and get back to you.

**Comment by VenkateshRavula** [comment]
The fix is merged to master. Now you can create the volume using the below code.

```
- name: Create a Volume with a volume template name 
  oneview_volume:
    config: '{{ config }}'
    state: present
    data:
      properties:
        name: 'Volume with template name'
        description: 'Test volume with template name'
      templateName: "{{ volume_template_name }}"
      isPermanent: false
  delegate_to: localhost
```

To test the fix please follow the below procedure-
- If you have installed collections through github, then pull the master and build and install the collections and run the playbook to test the fix.
- If you have installed through galaxy, then please wait for our next release.
