### ISSUE TITLE
The SDK doesn't manage workload-profile

### ISSUE THREAD

**Issue by VenkateshRavula** [HewlettPackard/oneview-ansible-collection#112]
### Scenario/Intent

The OneView Ansible SDK should handle workload profile and add additionnal BIOS settings related to the selected workload profile

When we create a server profile or a server profile template thru the OneView GUI , additionnal parameters are included with the workload profile and we should have the same behaviour using the SDK.

The OneView SDK shoud provide a simple solution to manage the workload profile and handle it-self the additional bios settings to add.

See the HPE documentation page 8:
https://support.hpe.com/hpesc/public/docDisplay?docId=a00016408en_us

### Environment Details

 - Docker Image :  hewlettpackardenterprise/hpe-oneview-sdk-for-ansible:v5.10.0-OV5.6
 - Python Version: 3.6.12
 - ansible: 2.7.7
 - OneView Synergy 5.20
 
### Steps to Reproduce

```
# cat example.yaml
---
- hosts: localhost    
  vars:
    ansible_python_interpreter: '/usr/local/bin/python3.6'
    config: 'oneview_dev.json'
    EnclosureGroupName: "ad23vec001"
    sptName: "test-spt"

  tasks:

  # We want to clone the Server Profile Template 
  # and the SDK doessn't accept the enclosureGroupUri and serverHardwareTypeUri parameters
  - name: "Create a Server Profile Template with "
    oneview_server_profile_template:
      config: "{{ config }}"
      state: present
      data:
        name: "{{ sptName }}"
        serverHardwareTypeName: 'SY 480 Gen10 1'
        serverProfileDescription: "my description"
        enclosureGroupName: 'vec1'
        bios:
          complianceControl: 'checked'
          manageBios: True
          overriddenSettings: [{'id': 'WorkloadProfile', 'value': 'Virtualization-MaxPerformance' }]
		  
# ansible-playbook -v example.yaml
```

### Expected Result

The SDK should add the BIOS settings of the workload profile : As example for the Virtualization-MaxPerformance Profile :

```
"server_profile_templates": [
        {
            "affinity": "Bay",
            "bios": {
                "complianceControl": "Checked",
                "manageBios": true,
                "overriddenSettings": [
                    {
                        "id": "WorkloadProfile",
                        "value": "Virtualization-MaxPerformance"
                    },
                    {
                        "id": "MinProcIdlePower",
                        "value": "NoCStates"
                    },
                    {
                        "id": "IntelUpiPowerManagement",
                        "value": "Disabled"
                    },
                    {
                        "id": "MinProcIdlePkgState",
                        "value": "NoState"
                    },
                    {
                        "id": "EnergyPerfBias",
                        "value": "MaxPerf"
                    },
                    {
                        "id": "UncoreFreqScaling",
                        "value": "Maximum"
                    },
                    {
                        "id": "PowerRegulator",
                        "value": "StaticHighPerf"
                    },
                    {
                        "id": "SubNumaClustering",
                        "value": "Enabled"
                    },
                    {
                        "id": "CollabPowerControl",
                        "value": "Disabled"
                    },
                    {
                       "id": "EnergyEfficientTurbo",
                        "value": "Disabled"
                    },
                    {
                        "id": "NumaGroupSizeOpt",
                        "value": "Clustered"
                    }
                ]
            },
[ .... ]
        }
    ]
}
```
 
### Actual Result

```
"server_profile_templates": [
        {
            "affinity": "Bay",
            "bios": {
                "complianceControl": "Checked",
                "manageBios": true,
                "overriddenSettings": [
                    {
                        "id": "WorkloadProfile",
                        "value": "Virtualization-MaxPerformance"
                    }
                ]
            },
[ .... ]
        }
    ]
}
```

I thank you to improve the SDK and handle the workload profile.
