### ISSUE TITLE
Allow renaming of OneView Server Hardware (or advise how to rename server hardware)

### ISSUE THREAD

**Issue by liamwh** [HewlettPackard/oneview-ansible-collection#128]
I have a server hardware item with the incorrect name and need to rename it using Ansible. Essentially wanting to rename the iLO hostname as well as the Server Hardware in OneView.

Attempting to add the Server Hardware to OneView with the new name (by using the below code) causes the error found at the bottom of this issue.

# Attempt:
```yaml
 - name: (HPE) Add Server Hardware to OneView
    hpe.oneview.oneview_server_hardware:
      hostname: "{{ oneview_address }}"
      username: "{{ oneview_username }}"
      password: "{{ oneview_password }}"
      api_version: "{{ oneview_api_version }}"
      auth_login_domain: "{{ oneview_auth_login_domain }}"
      state: present
      data:
        hostname: "{{ management_card_hostname }}"
        username: "{{ management_card_username }}"
        password: "{{ management_card_password }}"
        licensingIntent: "OneView"
        force: false
        configurationState: "Managed"
    delegate_to: localhost
```

# Issue:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: hpeOneView.exceptions.HPEOneViewTaskError: The server hardware has already been added as {"name":"obscured","uri":"/rest/server-hardware/obscured"}.
```

# Manual Process
- Login to iLO
- Click on Network
- Click on iLO Dedicated Network Port
- Click on General
- Change iLO Subsystem Name (as shown below)
   ![Screenshot 2021-07-19 at 13 59 05](https://user-images.githubusercontent.com/23312359/126156728-826dbfb9-3c87-46af-a23b-916572f82898.png)
- Reset iLO
