### ISSUE TITLE
oneview_server_profile: Server profile template uri is not updated

### ISSUE THREAD

**Issue by liamwh** [HewlettPackard/oneview-ansible-collection#161]
Situation:

We want to update a server profile to use a different server profile template by specifying the server profile template uri as part of the oneview_server_profile module.

Code used to repeat:

```yaml
- name: "{{ esx_hostname }}: Gather facts about Server Profile by uri"
  hpe.oneview.oneview_server_profile_facts:
    hostname: "{{ oneview_address }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_auth_login_domain }}"
    uri: "{{ server_profile_uri }}"
  delegate_to: localhost
  register: server_profile_facts

- name: "{{ esx_hostname }}: Gather facts about specified Server Profile Template by name"
  hpe.oneview.oneview_server_profile_template_facts:
    hostname: "{{ oneview_address }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    name: "{{ server_profile_template }}"
  register: server_profile_template_facts

- name: "{{ esx_hostname }}: Ensure server profile is compliant"
  hpe.oneview.oneview_server_profile:
    hostname: "{{ oneview_address }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_auth_login_domain }}"
    state: compliant
    data:
      name: "{{ esx_hostname }}"
      serverProfileTemplateUri: "{{ server_profile_template_uri }}" # This line here is not changing the URI of the server profile template for the server profile
      serverHardwareUri: "{{ server_hardware_uri }}"
      description: "Configured by Ansible."
  delegate_to: localhost
  notify: "refresh server hardware"
```

Actual result, the server profile template uri is not updated:
![Screenshot 2021-12-07 at 16 52 58](https://user-images.githubusercontent.com/23312359/145062601-73928720-ec77-4eda-8837-b248b2a079a5.png)
