### ISSUE TITLE
Firmware-bundle - Upload of compsig file fails, hotfix not present

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/oneview-ansible-collection#168]
## Scenario/Intent

Hello,

I am trying upload spp, hotfix and compsig files to OneView using the `oneview_firmware_bundle` plugin. I am testing the upload of an hotfix and its two associated compsig file, however the upload fails with the compsig files.

### Input data

`- spp_list: ["<absolute_path>/firmware-ilo5-2.60-1.1.x86_64.rpm", "<absolute_path>/firmware-ilo5-2.60-1.1.x86_64_part1.compsig", "<absolute_path>/firmware-ilo5-2.60-1.1.x86_64_part2.compsig"]
`
### upload.yml

```
- name: Create fact to get the extension of the input var file
  set_fact:
    __file_extension: ""

- name: Set fact with the extension of the input var file
  set_fact:
    __file_extension : [...]

#if file (hotfix, spp) doesn't have a compsig extension, do this task
- name: Upload the firmware bundle
  oneview_firmware_bundle:
    config: "{{ __config }}"
    state: present
    file_path: "{{ __spp_file_path }}"
  when: "'compsig' not in __file_extension" #here __file_extension = "rpm" for the first file upload

#if file has a compsig extension (signature), do this task
- name: Upload the firmware bundle
  oneview_firmware_bundle:
    config: "{{ __config }}"
    state: add_signature
    file_path: "{{ __spp_file_path }}"
  when: "'compsig' in __file_extension" #here __file_extension = "compsig" for the 2nd and 3rd file upload
```

## Environment Details

- OneView Ansible Collection: v6.5.0
- OneView Appliance Version: 6.10
- Ansible version: 2.9.6
- Python version: 3.6.10

## Expected Result

The consecutive upload of the hotfix and its compsig files on OneView.

## Actual Result

Result of the `ansible-playbook` command

`#First loop iteration to upload the hotfix`

```
TASK [Upload the firmware bundle] **********************************************************************************
changed: [localhost] => {
    "ansible_facts": {
        "firmware_bundle": {
            "baselineShortName": "Not_Applicable",
            "bundleSize": 33932254,
            "bundleType": "Hotfix",
            "category": "firmware-drivers",
            "created": "2022-02-17T10:01:45.113Z",
            "description": "This package contains HPE Integrated Lights-Out 5 firmware",
            "eTag": "2022-02-17T10:04:33.117Z",
            "esxiOsDriverMetaData": [
                "Not_Applicable"
            ],
            "fwComponents": [
                {
                    "componentVersion": "2.60",
                    "fileName": "firmware-ilo5-2.60-1.1.x86_64.rpm",
                    "name": "HPE Integrated Lights-Out 5 firmware",
                    "swKeyNameList": [
                        "RI11"
                    ]
                }
            ],
            "hotfixes": [],
            "hpsumVersion": "Not_Applicable",
            "isoFileName": "Not_Applicable",
            "lastTaskUri": "/rest/tasks/7e520ed5-df90-4132-8cdd-61c35253c395",
            "locations": {
                "/rest/repositories/internal": "Internal"
            },
   [...]
    },
    "msg": "Firmware Bundle or Hotfix added successfully."
}

# Second loop iteration to upload the compsig files

TASK [Upload the firmware bundle] **********************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": null,
            "auth_login_domain": null,
            "config": "config.json",
            "file_path": "<aboslute_path>/firmware-ilo5-2.60-1.1.x86_64_part1.compsig",
            "hostname": null,
            "image_streamer_hostname": null,
            "password": null,
            "state": "add_signature",
            "username": null,
            "validate_etag": true
        }
    },
    "msg": "Hotfix is not present."
}

```
