### ISSUE TITLE
Atomic assign server hardware

### ISSUE THREAD

**Issue by WimBerkhof** [HewlettPackard/oneview-ansible-collection#169]
Using Ansible we deploy VMware ESX hosts on HPE Synergy infrastructure.

We like to run tasks in parallel to reduce the total runtime. 
Creating a single server profile takes about 10 minutes.

```
name: Creating Server Profile from Server Profile Template "{{ server_template }}"
      throttle: 1       # select server hardware once
      oneview_server_profile:
        config: "{{ config }}"
        data:
          serverProfileTemplateName: "{{ server_template }}"
          name: "{{ inventory_hostname }}"
```

When assigning hardware tasks for multiple hosts will select the very same compute.
Thus only one task succeeds, the others fail. Therefor 'throttle: 1' is included to single thread this task.

Assigning hardware should be atomic, ie. a server blade should be locked and a subsequent
'assign hardware' call should return the next available compute.
