### ISSUE TITLE
Appliance network settings - updating DNS fails

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/oneview-ansible-collection#177]
## Scenario/Intent

Hello,

I am trying to update the DNS settings in the network appliance of OneView however I am getting an error when running the playbook. Am I missing something necessary for the task ?

### main.yml

```
- name: Update dns servers of the network interface
  hpe.oneview.oneview_appliance_network_interfaces:
    state: present
    hostname: "{{ oneview_hostname }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_auth_login_domain }}"
    api_version: "{{ oneview_api_version }}"
    data:
      macAddress: "{{ macAddress }}"
      ipv4NameServers: "{{ network_settings }}"
  delegate_to: localhost
```

Example of input DNS settings: `network_settings: ["firstIpAddress", "secondIpAddress"]`

## Environment Details

- OneView Ansible Collection: v6.6.0
- OneView Appliance Version: 6.10
- Ansible version: 2.9.6
- Python version: 3.8.10

## Expected Result

The DNS (preferred or alternate) ips are updated with the correct input.

## Actual Result

```
raise HPEOneViewTaskError(msg, error_code)\nhpeOneView.exceptions.HPEOneViewTaskError: Supplied IP address <ip @ of the OneView> is duplicate for one or more fields.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```
