### ISSUE TITLE
SNMPv3 users - Idempotency issue

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/oneview-ansible-collection#179]
## Scenario/Intent

Hello,

I am creating SNMPv3 users via an Ansible task however running the same code twice with the same user input leads to an error.

### main.yml

```
- name: Create snmpv3 users
  oneview_appliance_device_snmp_v3_users:
    config: "{{ config }}"
    state: present
    data:
        userName: "{{ username }}"
        securityLevel: "{{ security_level }}"
        authenticationProtocol: "{{ authentication_protocol }}"
        authenticationPassphrase: "{{ authentication_passphrase }}"
        privacyProtocol: "{{ privacy_protocol }}"
        privacyPassphrase: "{{ privacy_passphrase }}"
  delegate_to: localhost
```

## Environment Details

- OneView Ansible Collection: v6.6.0
- OneView Appliance Version: 6.10
- Ansible version: 2.9.6
- Python version: 3.8.10

## Expected Result

We have idempotency when we run the same playbook with the same SNMPv3 user input data multiple times.

## Actual Result

```
TASK [snmpv3 : Create snmpv3 users] ******************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: hpeOneView.exceptions.HPEOneViewException: ('The supplied user name already exists.', {'errorCode': 'USER_ALREADY_EXIST', 'message': 'The supplied user name already exists.', 'details': '', 'messageParameters': [None], 'recommendedActions': ['Provide a different SNMPv3 user name and retry the operation.'], 'errorSource': None, 'nestedErrors': [], 'data': {}})

PLAY RECAP *******************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```
