### ISSUE TITLE
SNMPv3 traps - creation fails

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/oneview-ansible-collection#180]
## Scenario/Intent

Hello,

I am trying to create multiple SMNPv3 traps associated with a SNMPv3 user however this end with an error. I do not know if the problem could come from the username (userId ?) used during the creation of the trap.

### main.yml

```
- name: Create snmpv3 trap
   oneview_appliance_device_snmp_v3_trap_destinations:
    config: "{{ config }}"
    state: present
    name: "{{ destination }}"
    data:
        destinationAddress: "{{ destination }}"
        port: "{{ port }}"
        userName: "{{ username }}"
  delegate_to: localhost
```

## Environment Details

- OneView Ansible Collection: v6.6.0
- OneView Appliance Version: 6.10
- Ansible version: 2.9.6
- Python version: 3.8.10

## Expected Result

Creation of a SNMPv3 trap is successful.

## Actual Result

```
TASK [snmpv3 : Create snmpv3 trap] *******************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'ApplianceDeviceSNMPv3Users' object is not subscriptable

line 140, in execute_module\n  File \"/tmp/ansible_hpe.oneview.oneview_appliance_device_snmp_v3_trap_destinations_payload_dqrs94qy/ansible_hpe.oneview.oneview_appliance_device_snmp_v3_trap_destinations_payload.zip/ansible_collections/hpe/oneview/plugins/modules/oneview_appliance_device_snmp_v3_trap_destinations.py\", line 153, in __replace_snmpv3_username_by_userid\nTypeError: 'ApplianceDeviceSNMPv3Users' object is not subscriptable\n",

PLAY RECAP *******************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```
