### ISSUE TITLE
oneview_logical_interconnect_group.py does not handle empty uplinksets

### ISSUE THREAD

**Issue by frippe75** [HewlettPackard/oneview-ansible-collection#221]
Created an empty uplinkset named 'Test'

Then went on to try to add some new networks to that LIG and the new Uplinkset.
```
      oneview_logical_interconnect_group:
        config: "{{ config }}"
        state: present
        data:
          name: 'LIG1'
          enclosureType: 'SY12000'
          uplinkSets:
            - name: 'Test'
              mode: 'Auto'
              networkType: 'Ethernet'
              networkNames:
                - 'VLAN_1100'
                - 'VLAN_1101'
```

It error out on:
```
/ansible_collections/hpe/oneview/plugins/modules/oneview_logical_interconnect_group.py\", line 323, in __replace_uplinkset_port_values\nTypeError: 'NoneType' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
```

Looking at the source code 
```
for uplinkSet in self.data['uplinkSets']:
                    existingLogicalPortConfigInfos = uplinkSet.get('logicalPortConfigInfos')
                    for item in existingLogicalPortConfigInfos:
```

Looks like the uplinkSet.get('logicalPortConfigInfos') returns nothing. Maybe check for this and handle accordingly?
