### ISSUE TITLE
Issues with installation / conflicts

### ISSUE THREAD

**Issue by joaofeteira** [HewlettPackard/oneview-ansible-collection#261]
Hi,

Following the steps for the installation: 
ansible-galaxy collection install hpe.oneview
ansible-galaxy collection install hpe.oneview --force

I try to launch a simple command just to test:
```
    - name: Gather Facts
      oneview_ethernet_network_facts:
        hostname: "HOST"
        username: "USERNAME"
        password: "PASSWORD"
        api_version: 5400
      no_log: true
```

And I get this output:
```
exit status 1. Output: ERROR! [DEPRECATED]: community.general.oneview_ethernet_network_facts has been removed. Use
│ community.general.oneview_ethernet_network_info instead. This feature was removed from community.general in version 3.0.0. Please update your playbooks.
```

If I try to perform the suggested change to oneview_ethernet_network_info I get:
```
The error was: ModuleNotFoundError: No module named 'hpOneView'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (hpOneView) on util's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

```

Any tips?

BR
