### ISSUE TITLE
server_hardware_facts - all server_firwmare issue

### ISSUE THREAD

**Issue by pawelfi** [HewlettPackard/oneview-ansible-collection#286]
Hello,

I used this kind of playbook:
```
- name: Gather all facts about a Server Hardware
  oneview_server_hardware_facts:
    hostname: IP_address
    username: administrator
    password: my_password
    api_version: 3200
    options:
      - firmwares               # optional
  delegate_to: localhost

- debug: var=server_hardware_firmwares
```

But his gives me back:
`"server_hardware_firmwares": VARIABLE IS NOT DEFINIED"`

**/oneview-ansible-collection/tree/master/plugins/modules/oneview_server_hardware_facts.py** has under line 221 this:
```

server_hardware_firmwares:
    description: Has all the facts about the firmwares inventory **across all servers.**
    returned: When requested, but can be null.
    type: dict
```

So I understand that i do not have to use **"name:"** - to gather information **"across all servers."**?

Could you please let me know how to gather information abut server firmware across all servers located on composer?

I can do it using loop, or a variable that holds all server names, but from example written looks that this kind of information should be gathered with simple playbook as i wrote.

Regards
Pawel
