### ISSUE TITLE
BUG: oneview_sas_logical_interconnect update_firmware has incorrect parameter in python code

### ISSUE THREAD

**Issue by tubatodd** [HewlettPackard/oneview-ansible-collection#303]
Found in `oneview-ansible-collection` 9.1 and still present in 9.2

`oneview_sas_logical_interconnect.py` line 190 is expecting an option of `install_firmware` but the "valid" option that is passed in the task is `update_firmware`. Changing like `190` to `update_firmware` executes a successful firmware update. Without this change the task is successful but nothing actually happens. 

Example Task
```
- name: Installs firmware to the member interconnects of a logical interconnect
  oneview_sas_logical_interconnect:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: update_firmware
    data:
      name: "{{ sas_logical_interconnect_name }}"
      firmware:
        command: "Stage"
        force: false
        sppUri: "{{ firmware_drivers[0]['uri'] }}"
  when: firmware_drivers is defined
  delegate_to: localhost
```
